all:
	g++ -o ../rtype ../OtterEngine/src/*.cpp ../OtterEngine/src/Music/*.cpp ../OtterEngine/src/SpriteManager/*.cpp ./src/*.cpp -I ../OtterEngine/include/SpriteManager/ -I ../OtterEngine/include/GUI/ -I ../OtterEngine/include/Music/ -I ./include/ -I ../OtterEngine/include/ -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system -ldl -std=c++11
